module.exports = [
  {
    start: 'Sep 24, 1867',
    end: 'Jul 8, 1872',
    party: 'Conservative',
    majority: true,
    seats: 100,
    total: 180,
    leader: 'John A. Macdonald',
  },
  {
    start: 'Sep 3, 1872',
    end: 'August 13, 1873',
    party: 'Conservative',
    majority: false,
    seats: 99,
    total: 200,
    leader: 'John A. Macdonald ',
  },
  {
    start: 'August 13, 1873',
    end: '1874 ',
    party: 'Liberal Party of Canada',
    majority: false,
    seats: 95,
    total: 200,
    // leader: 'Alexander Mackenzie',
  },
  {
    start: 'Feb 21, 1874',
    end: 'Aug 16, 1878',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 129,
    total: 206,
    leader: 'Alexander Mackenzie',
  },
  {
    start: 'Nov 21, 1878',
    end: 'May 18, 1882',
    party: 'Conservative',
    majority: true,
    seats: 134,
    total: 206,
    leader: 'John A. Macdonald',
  },
  {
    start: 'Aug 7, 1882',
    end: 'Jan 15, 1887',
    party: 'Conservative',
    majority: true,
    seats: 133,
    total: 211,
    leader: 'John A. Macdonald',
  },
  {
    start: 'Apr 13, 1887',
    end: 'Feb 3, 1891',
    party: 'Conservative',
    majority: true,
    seats: 122,
    total: 215,
    leader: 'John A. Macdonald',
  },
  {
    start: 'Apr 7, 1891',
    end: 'Apr 24, 1896',
    party: 'Conservative',
    majority: true,
    seats: 117,
    total: 215,
    leader: 'John A. Macdonald',
  },
  {
    start: 'Jul 13, 1896',
    end: 'Oct 9, 1900',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 117,
    total: 213,
    leader: 'Wilfrid Laurier',
  },
  {
    start: 'Dec 5, 1900',
    end: 'Sep 29, 1904',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 128,
    total: 213,
    leader: 'Wilfrid Laurier',
  },
  {
    start: 'Dec 15, 1904',
    end: 'Sep 17, 1908',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 137,
    total: 214,
    leader: 'Wilfrid Laurier',
  },
  {
    start: 'Dec 3, 1908',
    end: 'Jul 29, 1911',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 133,
    total: 221,
    leader: 'Wilfrid Laurier',
  },
  {
    start: 'Oct 7, 1911',
    end: 'Oct 6, 1917',
    party: 'Conservative',
    majority: true,
    seats: 132,
    total: 221,
    leader: 'Robert Borden',
  },
  {
    start: 'Mar 16, 1918',
    end: 'Oct 4, 1921',
    party: 'Conservative',
    majority: true,
    seats: 153,
    total: 235,
    leader: 'Robert Borden',
  },
  {
    start: 'Mar 16, 1918',
    end: 'Oct 4, 1921',
    party: 'Conservative',
    majority: true,
    seats: 153,
    total: 235,
    leader: 'Arthur Meighen',
  },
  {
    start: 'Jan 15, 1922',
    end: 'Sep 5, 1925',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 118,
    total: 235,
    leader: 'William Lyon Mackenzie King',
  },
  // {
  //   start: 'Dec 7, 1925',
  //   end: 'Dec 7, 1925',
  //   party: 'Liberal Party of Canada',
  //   majority: false,
  //   seats: 100,
  //   total: 245,
  //   leader: 'William Lyon Mackenzie King',
  // },
  {
    start: 'Dec 7, 1925',
    end: 'Jul 2, 1926',
    party: 'Conservative',
    majority: false,
    seats: 115,
    total: 245,
    leader: 'Arthur Meighen',
  },
  {
    start: 'Nov 2, 1926',
    end: 'May 30, 1930',
    party: 'Liberal Party of Canada',
    majority: false,
    seats: 116,
    total: 245,
    leader: 'William Lyon Mackenzie King',
  },
  {
    start: 'Aug 18, 1930',
    end: 'Aug 14, 1935',
    party: 'Conservative',
    majority: true,
    seats: 134,
    total: 245,
    leader: 'Richard Bennett',
  },
  {
    start: 'Nov 9, 1935',
    end: 'Jan 25, 1940',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 173,
    total: 245,
    leader: 'William Lyon Mackenzie King',
  },
  {
    start: 'Apr 17, 1940',
    end: 'Apr 16, 1945',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 179,
    total: 245,
    leader: 'William Lyon Mackenzie King',
  },
  {
    start: 'Aug 9, 1945',
    end: 'Apr 30, 1949',
    party: 'Liberal Party of Canada',
    majority: false,
    seats: 118,
    total: 245,
    leader: 'William Lyon Mackenzie King',
  },
  {
    start: 'Aug 29, 1949',
    end: 'Jun 13, 1953',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 191,
    total: 262,
    leader: 'Louis St. Laurent',
  },
  {
    start: 'Oct 8, 1953',
    end: 'Apr 12, 1957',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 169,
    total: 265,
    leader: 'Louis St. Laurent',
  },
  {
    start: 'Aug 8, 1957',
    end: 'Feb 1, 1958',
    party: 'Conservative',
    majority: false,
    seats: 111,
    total: 265,
    leader: 'John Diefenbaker',
  },
  {
    start: 'Apr 30, 1958',
    end: 'Apr 19, 1962',
    party: 'Conservative',
    majority: true,
    seats: 208,
    total: 265,
    leader: 'John Diefenbaker',
  },
  {
    start: 'Jul 18, 1962',
    end: 'Feb 6, 1963',
    party: 'Conservative',
    majority: false,
    seats: 116,
    total: 265,
    leader: 'John Diefenbaker',
  },
  {
    start: 'May 8, 1963',
    end: 'Sep 8, 1965',
    party: 'Liberal Party of Canada',
    majority: false,
    seats: 128,
    total: 265,
    leader: 'Lester B. Pearson',
  },
  {
    start: 'Dec 9, 1965',
    end: 'Apr 23, 1968',
    party: 'Liberal Party of Canada',
    majority: false,
    seats: 131,
    total: 265,
    leader: 'Lester B. Pearson',
  },
  {
    start: 'Jul 25, 1968',
    end: 'Sep 1, 1972',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 154,
    total: 264,
    leader: 'Pierre Trudeau',
  },
  {
    start: 'Nov 20, 1972',
    end: 'May 9, 1974',
    party: 'Liberal Party of Canada',
    majority: false,
    seats: 109,
    total: 264,
    leader: 'Pierre Trudeau',
  },
  {
    start: 'Jul 31, 1974',
    end: 'Mar 26, 1979',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 141,
    total: 264,
    leader: 'Pierre Trudeau',
  },
  {
    start: 'Jun 11, 1979',
    end: 'Dec 14, 1979',
    party: 'Conservative',
    majority: false,
    seats: 136,
    total: 282,
    leader: 'Joe Clark',
  },
  {
    start: 'Mar 10, 1980',
    end: 'Jul 9, 1984',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 147,
    total: 282,
    leader: 'Pierre Trudeau',
  },
  {
    start: 'Sep 24, 1984',
    end: 'Oct 1, 1988',
    party: 'Conservative',
    majority: true,
    seats: 211,
    total: 282,
    leader: 'Brian Mulroney',
  },
  {
    start: 'Dec 12, 1988',
    end: 'Sep 8, 1993',
    party: 'Conservative',
    majority: true,
    seats: 169,
    total: 295,
    leader: 'Brian Mulroney',
  },
  {
    start: 'Nov 15, 1993',
    end: 'Apr 27, 1997',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 177,
    total: 295,
    leader: 'Jean Chrétien',
  },
  {
    start: 'Jun 23, 1997',
    end: 'Oct 22, 2000',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 155,
    total: 301,
    leader: 'Jean Chrétien',
  },
  {
    start: 'Jun 23, 1997',
    end: 'Oct 22, 2000',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 155,
    total: 301,
    leader: 'Jean Chrétien',
  },
  {
    start: 'Dec 18, 2000',
    end: 'May 23, 2004',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 172,
    total: 301,
    leader: 'Jean Chrétien',
  },
  {
    start: 'Dec 18, 2000',
    end: 'May 23, 2004',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 172,
    total: 301,
    leader: 'Jean Chrétien',
  },
  {
    start: 'Jul 19, 2004',
    end: 'Nov 29, 2005',
    party: 'Liberal Party of Canada',
    majority: false,
    seats: 135,
    total: 308,
    leader: 'Paul Martin',
  },
  {
    start: 'Feb 13, 2006',
    end: 'Sep 7, 2008',
    party: 'Conservative',
    majority: false,
    seats: 124,
    total: 308,
    leader: 'Stephen Harper',
  },
  {
    start: 'Nov 4, 2008',
    end: 'Mar 26, 2011',
    party: 'Conservative',
    majority: false,
    seats: 143,
    total: 308,
    leader: 'Stephen Harper',
  },
  {
    start: 'May 23, 2011',
    end: 'Aug 2, 2015',
    party: 'Conservative',
    majority: true,
    seats: 166,
    total: 308,
    leader: 'Stephen Harper',
  },
  {
    start: 'Dec 3, 2015',
    end: 'Sep 11, 2019',
    party: 'Liberal Party of Canada',
    majority: true,
    seats: 184,
    total: 338,
    leader: 'Justin Trudeau',
  },
  {
    start: 'Dec 5, 2019',
    end: 'TBD',
    party: 'Liberal Party of Canada',
    majority: false,
    seats: 157,
    total: 338,
    leader: 'Justin Trudeau',
  },
]
