export default {
  2026: [
    { id: '2026/06/sundial', label: 'Sundial' },
  ],
  2025: [],
  2024: [],
  2023: [
    { id: '2023/canada-homeowners', label: 'Canada Homeowners' },
    { id: '2023/dst-changes', label: 'Daylight Savings Changes' },
    { id: '2023/timezone-offsets', label: 'Timezone Offsets' },
  ],
  2022: [
    { id: '2022/accumulated-units', label: 'Accumulated Units' },
    { id: '2022/aspect-ratios', label: 'Aspect Ratios' },
    { id: '2022/bluejays-calendar', label: 'Blue Jays Calendar' },
    { id: '2022/construction-map', label: 'Construction Map' },
    { id: '2022/missing-middle', label: 'Missing Middle' },
    { id: '2022/one-of', label: 'One of' },
    { id: '2022/pipeline', label: 'Pipeline' },
    { id: '2022/population-growth', label: 'Population Growth' },
    { id: '2022/riding-sankey', label: 'Riding Sankey' },
    { id: '2022/toronto-construction', label: 'Toronto Construction' },
    { id: '2022/toronto-council', label: 'Toronto Council' },
    { id: '2022/toronto-elections', label: 'Toronto Elections' },
    { id: '2022/transit-map', label: 'Transit Map' },
  ],
  2021: [
    { id: '2021/cbc-radio-schedule', label: 'CBC Radio Schedule' },
    { id: '2021/computers-and-typewriters', label: 'Computers and Typewriters' },
  ],
  2020: [
    { id: '2020/skydome-roof-by-year', label: 'Skydome Roof by Year' },
    { id: '2020/snowfall-in-canada', label: 'Snowfall in Canada' },
    { id: '2020/stanley-cups-in-canada', label: 'Stanley Cups in Canada' },
    { id: '2020/sunset-direction', label: 'Sunset Direction' },
    { id: '2020/toronto-budget', label: 'Toronto Budget' },
    { id: '2020/transit-projects-canada', label: 'Transit Projects Canada' },
    { id: '2020/weeks-of-the-year', label: 'Weeks of the Year' },
    { id: '2020/year-in-toronto', label: 'Year in Toronto' },
  ],
  2019: [
    { id: '2019/baseball-schedule', label: 'Baseball Schedule' },
    { id: '2019/break-up-the-year', label: 'Break Up the Year' },
    { id: '2019/daylight-by-latitude', label: 'Daylight by Latitude' },
    { id: '2019/generations-of-people', label: 'Generations of People' },
    { id: '2019/nhl-arenas', label: 'NHL Arenas' },
    { id: '2019/nhl-history', label: 'NHL History' },
    { id: '2019/nhl-team-performance', label: 'NHL Team Performance' },
    { id: '2019/ontario-landfills', label: 'Ontario Landfills' },
    { id: '2019/ontario-line', label: 'Ontario Line' },
    { id: '2019/rain-in-toronto', label: 'Rain in Toronto' },
  ],
  2018: [
    { id: '2018/baseball-season', label: 'Baseball Season' },
    { id: '2018/lunar-astronauts', label: 'Lunar Astronauts' },
    { id: '2018/sports-by-city', label: 'Sports by City' },
    { id: '2018/weather-by-latitude', label: 'Weather by Latitude' },
  ],

}