// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026-09-20, 4:50:30 p.m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/spencer/mountain/web/graphs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/spencer/mountain/web/graphs/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/spencer/mountain/web/graphs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/spencer/mountain/web/graphs/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/spencer/mountain/web/graphs/plugins/**/*.{js,ts,mjs}","/Users/spencer/mountain/web/graphs/composables/**/*.{js,ts,mjs}","/Users/spencer/mountain/web/graphs/utils/**/*.{js,ts,mjs}","/Users/spencer/mountain/web/graphs/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/spencer/mountain/web/graphs/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/spencer/mountain/web/graphs/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/spencer/mountain/web/graphs/app.config.{js,ts,mjs}","/Users/spencer/mountain/web/graphs/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;